# Remove the existing 'Goods' directory if it exists, and create a new one
[ -d "Goods" ] && rm -rf Goods
mkdir Goods

# Process each unique sample
for d in `ls *.fastq | cut -f1 -d "_" | sort | uniq`
do
    # Use 'prinseq-lite.pl' to filter reads based on quality
    perl prinseq-lite.pl -fastq "${d}_1.fastq" -fastq2 "${d}_2.fastq" -min_qual_mean 25 -out_format 3 -out_bad null


    # Remove any singletons generated by 'prinseq-lite.pl'
    rm *singletons*

    # Get the names of the filtered forward and reverse read files
    forwd=$(ls *1_prinseq_good*)
    backd=$(ls *2_prinseq_good*)

    # Move the filtered forward and reverse read files to the 'Goods' directory
    mv "$forwd" Goods/"${d}_1.fastq"
    mv "$backd" Goods/"${d}_2.fastq" 
done
